<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><IsPackable>false</IsPackable>
    <B3LibraryPath Condition="'$(B3LibraryPath)' == ''">../../build/b3-library/B3Library.dll</B3LibraryPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DafnyB3Host/DafnyB3Host.csproj" />
    <ProjectReference Include="../DafnyB3Protocol/DafnyB3Protocol.csproj" />
    <Reference Include="B3Library"><HintPath>$(B3LibraryPath)</HintPath><Private>true</Private></Reference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>
