// Regression for contextual subset domains of direct function-result lambdas.
// RUN: echo "original (refresh:false, contextual:false)" > "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-original.dfy" --type-system-refresh:false --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:false, contextual:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-original.dfy" --type-system-refresh:false --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, contextual:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-original.dfy" --type-system-refresh:true --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, contextual:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-original.dfy" --type-system-refresh:true --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:false, contextual:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-positive.dfy" --type-system-refresh:false --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:false, contextual:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-positive.dfy" --type-system-refresh:false --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:true, contextual:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-positive.dfy" --type-system-refresh:true --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:true, contextual:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-4949-positive.dfy" --type-system-refresh:true --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:false, contextual:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-negative.dfy" --type-system-refresh:false --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:false, contextual:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-negative.dfy" --type-system-refresh:false --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:true, contextual:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-negative.dfy" --type-system-refresh:true --contextual-lambda-domains:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:true, contextual:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-4949-negative.dfy" --type-system-refresh:true --contextual-lambda-domains:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: %diff "%s.expect" "%t"
