// Regression: datatype cloning must apply converters to erased subset fields.
// RUN: echo "original-false-verify" > "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-5881-original.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "original-false-build" >> "%t"
// RUN: %exits-with 2 %baredafny build "%S/Inputs/git-issue-5881-original.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "original-true-verify" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-5881-original.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "original-true-build" >> "%t"
// RUN: %exits-with 0 %baredafny build "%S/Inputs/git-issue-5881-original.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "plain-subset-false-run" >> "%t"
// RUN: %exits-with 0 %baredafny run "%S/Inputs/git-issue-5881-plain-subset.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "plain-subset-true-run" >> "%t"
// RUN: %exits-with 0 %baredafny run "%S/Inputs/git-issue-5881-plain-subset.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "nested-subset-false-run" >> "%t"
// RUN: %exits-with 0 %baredafny run "%S/Inputs/git-issue-5881-nested-subset.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "nested-subset-true-run" >> "%t"
// RUN: %exits-with 0 %baredafny run "%S/Inputs/git-issue-5881-nested-subset.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "trait-subset-false-run" >> "%t"
// RUN: %exits-with 2 %baredafny run "%S/Inputs/git-issue-5881-trait-subset.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "trait-subset-true-run" >> "%t"
// RUN: %exits-with 0 %baredafny run "%S/Inputs/git-issue-5881-trait-subset.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "bad-subset-false-run" >> "%t"
// RUN: %exits-with 4 %baredafny run "%S/Inputs/git-issue-5881-bad-subset.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "bad-subset-true-run" >> "%t"
// RUN: %exits-with 4 %baredafny run "%S/Inputs/git-issue-5881-bad-subset.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "bad-trait-false-run" >> "%t"
// RUN: %exits-with 2 %baredafny run "%S/Inputs/git-issue-5881-bad-trait.dfy" --general-traits=datatype --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: echo "bad-trait-true-run" >> "%t"
// RUN: %exits-with 2 %baredafny run "%S/Inputs/git-issue-5881-bad-trait.dfy" --general-traits=datatype --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 >> "%t"
// RUN: %diff "%s.expect" "%t"
