// Regression for the default-off shared additional-axioms option: heap succession is reflexive at the
// previous heap of a two-state function used as a value (dafny-lang/dafny#1461).  Without the option, the
// original and three of the positive cases fail.
// RUN: echo "original, option off (type-system-refresh:false)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1461-original.dfy" --type-system-refresh:false --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "original, option off (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1461-original.dfy" --type-system-refresh:true --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive, option off (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1461-positive.dfy" --type-system-refresh:false --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "original (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1461-original.dfy" --additional-axioms --type-system-refresh:false --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1461-positive.dfy" --additional-axioms --type-system-refresh:false --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 --bprint "%t.bpl" >> "%t"
// RUN: echo "negative (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1461-negative.dfy" --additional-axioms --type-system-refresh:false --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "original (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1461-original.dfy" --additional-axioms --type-system-refresh:true --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1461-positive.dfy" --additional-axioms --type-system-refresh:true --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "negative (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1461-negative.dfy" --additional-axioms --type-system-refresh:true --allow-axioms --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "Boogie, extensional heaps (typeEncoding:m)" >> "%t"
// RUN: dotnet tool run boogie -typeEncoding:m -useBaseNameForFileName '-proc:Issue1461_*' -timeLimit:60 -proverOpt:PROVER_PATH=%review-z3 "%t.bpl" "%S/Inputs/git-issue-1461.bpl" >> "%t"
// RUN: echo "Boogie, Dafny's encoding (typeEncoding:a)" >> "%t"
// RUN: dotnet tool run boogie -typeEncoding:a -useBaseNameForFileName '-proc:Issue1461_*' -timeLimit:60 -proverOpt:PROVER_PATH=%review-z3 "%t.bpl" "%S/Inputs/git-issue-1461.bpl" >> "%t"
// RUN: %diff "%s.expect" "%t"
