// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-rank-set.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" > "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-rank-set.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-rank-map.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-rank-map.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-map-carrier-set.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-map-carrier-set.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-map-carrier-map.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/git-issue-82-map-carrier-map.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %baredafny verify "%S/Inputs/git-issue-82-rank-positive.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %baredafny verify "%S/Inputs/git-issue-82-rank-positive.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" >> "%t"
// RUN: %diff "%s.expect" "%t"
