// Regression for bitvector map lookup keys; raw programs are in Inputs.
// RUN: echo "original (refresh:false, axioms:false, keys:false)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:false --additional-axioms:false --bitvector-map-keys:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:false, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:false --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:false, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-positive.dfy" --type-system-refresh:false --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:false, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-negative.dfy" --type-system-refresh:false --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:false, axioms:true, keys:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:false --additional-axioms:true --bitvector-map-keys:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:false, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:false --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:false, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-positive.dfy" --type-system-refresh:false --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:false, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-negative.dfy" --type-system-refresh:false --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, axioms:false, keys:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:true --additional-axioms:false --bitvector-map-keys:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:true --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:true, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-positive.dfy" --type-system-refresh:true --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:true, axioms:false, keys:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-negative.dfy" --type-system-refresh:true --additional-axioms:false --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, axioms:true, keys:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:true --additional-axioms:true --bitvector-map-keys:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "original (refresh:true, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-original.dfy" --type-system-refresh:true --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "positive (refresh:true, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/git-issue-1962-positive.dfy" --type-system-refresh:true --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: echo "negative (refresh:true, axioms:true, keys:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-1962-negative.dfy" --type-system-refresh:true --additional-axioms:true --bitvector-map-keys:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:30 --cores:1 >> "%t"
// RUN: %diff "%s.expect" "%t"
