// RUN: echo "Arithmetic solver selection"
// RUN: %baredafny verify --solver-path "%z3" --type-system-refresh:false --arithmetic-solver 6 --resource-limit 20000000 "%s" > "%t"
// RUN: %diff "%s.expect" "%t"
// RUN: %baredafny verify --solver-path "%z3" --type-system-refresh:true --arithmetic-solver 6 --resource-limit 20000000 "%s" > "%t"
// RUN: %diff "%s.expect" "%t"
// RUN: %baredafny verify --solver-path "%z3" --boogie "/proc:__NoProcedureMatches__" --bprint "%t.bpl" "%S/Inputs/github-issue-31-modules.dfy" > "%t"
// RUN: %OutputCheck --file-to-check "%t_Inherited.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Empty.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Two.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Six.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %baredafny verify --solver-path "%z3" --arithmetic-solver 2 --boogie "/proc:__NoProcedureMatches__" --bprint "%t.bpl" "%S/Inputs/github-issue-31-modules.dfy" > "%t"
// RUN: %OutputCheck --file-to-check "%t_Inherited.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Empty.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Two.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Six.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %baredafny verify --solver-path "%z3" --arithmetic-solver 6 --boogie "/proc:__NoProcedureMatches__" --bprint "%t.bpl" "%S/Inputs/github-issue-31-modules.dfy" > "%t"
// RUN: %OutputCheck --file-to-check "%t_Inherited.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %OutputCheck --file-to-check "%t_Empty.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %OutputCheck --file-to-check "%t_Two.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Six.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %baredafny verify --solver-path "%z3" "%S/Inputs/github-issue-31.toml" > "%t"
// RUN: %diff "%s.expect" "%t"
// RUN: %baredafny verify --solver-path "%z3" --arithmetic-solver 6 --solver-option O:smt.arith.solver=2 --resource-limit 20000000 "%s" > "%t"
// RUN: %diff "%s.expect" "%t"
// RUN: %baredafny verify --solver-path "%z3" --arithmetic-solver 2 --boogie "/proc:__NoProcedureMatches__" --bprint "%t.bpl" "%S/Inputs/github-issue-31-modules.toml" > "%t"
// RUN: %OutputCheck --file-to-check "%t_Inherited.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Six.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %baredafny /compile:0 /proc:__NoProcedureMatches__ "/print:%t.bpl" "%S/Inputs/github-issue-31-modules.dfy" > "%t"
// RUN: %OutputCheck --file-to-check "%t_Inherited.bpl" "%S/Inputs/github-issue-31-solver2.check"
// RUN: %OutputCheck --file-to-check "%t_Six.bpl" "%S/Inputs/github-issue-31-solver6.check"
// RUN: %exits-with 1 %baredafny verify --arithmetic-solver=-1 "%s" 2> "%t"
// RUN: %OutputCheck --file-to-check "%t" "%S/Inputs/github-issue-31-invalid.check"
// RUN: %exits-with 1 %baredafny verify --arithmetic-solver=7 "%s" 2> "%t"
// RUN: %OutputCheck --file-to-check "%t" "%S/Inputs/github-issue-31-invalid.check"

lemma Mod8To4(d: int) requires d % 8 == 0 ensures d % 4 == 0 { }

lemma Mod8To2(d: int) requires d % 8 == 0 ensures d % 2 == 0 { }
