// Regression: exact-let bodies preserve the enclosing function self-call allowance.
// RUN: echo "original (type-system-refresh:false, additional-axioms:false)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-original.dfy" --type-system-refresh:false --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "original (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-original.dfy" --type-system-refresh:false --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "original (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-original.dfy" --type-system-refresh:true --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "original (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-original.dfy" --type-system-refresh:true --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "negative (type-system-refresh:false, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-negative.dfy" --type-system-refresh:false --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "negative (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-negative.dfy" --type-system-refresh:false --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "negative (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-negative.dfy" --type-system-refresh:true --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "negative (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-negative.dfy" --type-system-refresh:true --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "positive (type-system-refresh:false, additional-axioms:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-166-positive.dfy" --type-system-refresh:false --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "positive (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-166-positive.dfy" --type-system-refresh:false --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "positive (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-166-positive.dfy" --type-system-refresh:true --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "positive (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-166-positive.dfy" --type-system-refresh:true --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "false-control (type-system-refresh:false, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-false-control.dfy" --type-system-refresh:false --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "false-control (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-false-control.dfy" --type-system-refresh:false --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "false-control (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-false-control.dfy" --type-system-refresh:true --additional-axioms:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: echo "false-control (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-166-false-control.dfy" --type-system-refresh:true --additional-axioms:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 --boogie "/normalizeDeclarationOrder:0" >> "%t"
// RUN: %diff "%s.expect" "%t"
