// Regression: substitute the resolved match decision tree without dropping proof obligations.
// RUN: echo "original (type-system-refresh:false)" > "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-original.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "original (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-original.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "if (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-if.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "if (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-if.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-positive.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-85-positive.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "negative (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-85-negative.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "negative (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-85-negative.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%z3" --verification-time-limit:60 --cores:1 >> "%t"
// RUN: %diff "%s.expect" "%t"
