// Regression for triggers on the existential domain of general map comprehensions.
// RUN: echo "membership (type-system-refresh:false, default)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings  >> "%t"
// RUN: echo "membership (type-system-refresh:false, --map-comprehension-domain-triggers=false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers=false >> "%t"
// RUN: echo "membership (type-system-refresh:false, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: echo "negative (type-system-refresh:false, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-negative.dfy" --solver-path "%z3" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: echo "malformed (type-system-refresh:false, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-32-malformed.dfy" --solver-path "%z3" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: echo "membership (type-system-refresh:true, default)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings  >> "%t"
// RUN: echo "membership (type-system-refresh:true, --map-comprehension-domain-triggers=false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers=false >> "%t"
// RUN: echo "membership (type-system-refresh:true, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-32-membership.dfy" --solver-path "%z3" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: echo "negative (type-system-refresh:true, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-32-negative.dfy" --solver-path "%z3" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: echo "malformed (type-system-refresh:true, --map-comprehension-domain-triggers)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-32-malformed.dfy" --solver-path "%z3" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --cores:1 --resource-limit:2000000 --verification-time-limit:30 --allow-warnings --map-comprehension-domain-triggers >> "%t"
// RUN: %diff "%s.expect" "%t"
