// Regression for pure callback allocation at the actual proof heap.
// Positive composition and current-heap allocation remain live while old allocation and false fail.
// RUN: echo "all (type-system-refresh:false, additional-axioms:false)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "inhabited-false (type-system-refresh:false, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=InhabitedFalse137. >> "%t"
// RUN: echo "old-capture (type-system-refresh:false, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=OldCapture137. >> "%t"
// RUN: echo "all (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "inhabited-false (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=InhabitedFalse137. >> "%t"
// RUN: echo "old-capture (type-system-refresh:false, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:false --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=OldCapture137. >> "%t"
// RUN: echo "all (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "inhabited-false (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=InhabitedFalse137. >> "%t"
// RUN: echo "old-capture (type-system-refresh:true, additional-axioms:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=false --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=OldCapture137. >> "%t"
// RUN: echo "all (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "inhabited-false (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=InhabitedFalse137. >> "%t"
// RUN: echo "old-capture (type-system-refresh:true, additional-axioms:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/git-issue-137-pure-callback-controls.dfy" --solver-path "%review-z3" --type-system-refresh:true --additional-axioms=true --cores:1 --resource-limit:2000000 --verification-time-limit:60 --show-snippets:false --use-basename-for-filename --error-limit:0 --filter-symbol=OldCapture137. >> "%t"
// RUN: %diff "%s.expect" "%t"
