// Regression: forall statement substitutions retain binder identity throughout their scope.
// RUN: echo "original (type-system-refresh:false)" > "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-99-original.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "original (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-99-original.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-99-positive.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "positive (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-99-positive.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "negative (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-99-negative.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: echo "negative (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-99-negative.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --solver-path "%review-z3" --resource-limit:16000000 --verification-time-limit:60 --cores:1 >> "%t"
// RUN: %diff "%s.expect" "%t"
