// Native literal identities and unchanged function argument checks.
// RUN: echo "positive (Z3 5.1.0, type-system-refresh:false)" > "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-74-positive.dfy" --solver-path "%review-z3" --additional-axioms --type-system-refresh:false --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "negative (Z3 5.1.0, type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-74-negative.dfy" --solver-path "%review-z3" --additional-axioms --type-system-refresh:false --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "positive (Z3 5.1.0, type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-74-positive.dfy" --solver-path "%review-z3" --additional-axioms --type-system-refresh:true --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "negative (Z3 5.1.0, type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-74-negative.dfy" --solver-path "%review-z3" --additional-axioms --type-system-refresh:true --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "positive (Z3 4.12.1, type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-74-positive.dfy" --solver-path "%review-z3-4.12.1" --additional-axioms --type-system-refresh:false --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "negative (Z3 4.12.1, type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-74-negative.dfy" --solver-path "%review-z3-4.12.1" --additional-axioms --type-system-refresh:false --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "positive (Z3 4.12.1, type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny verify "%S/Inputs/github-issue-74-positive.dfy" --solver-path "%review-z3-4.12.1" --additional-axioms --type-system-refresh:true --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: echo "negative (Z3 4.12.1, type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-74-negative.dfy" --solver-path "%review-z3-4.12.1" --additional-axioms --type-system-refresh:true --cores:1 --resource-limit:200000 --verification-time-limit:0 --show-snippets:false --use-basename-for-filename --error-limit:0 >> "%t"
// RUN: %diff "%s.expect" "%t"
