// Regression for ordinal-sized quantifier domains in extreme recursion.
// RUN: echo "github-issue-38-accepted.dfy (type-system-refresh:false)" > "%t"
// RUN: %exits-with 0 %baredafny resolve "%S/Inputs/github-issue-38-accepted.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-accepted.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny resolve "%S/Inputs/github-issue-38-accepted.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-finite-proof.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-38-finite-proof.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-finite-proof.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-38-finite-proof.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-greatest.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-greatest.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-greatest.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-greatest.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-hidden.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-hidden.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-hidden.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-hidden.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-least-rank.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least-rank.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-least-rank.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least-rank.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-least-universal-iset.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least-universal-iset.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-least-universal-iset.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least-universal-iset.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-least.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-least.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny verify "%S/Inputs/github-issue-38-least.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-nat-accepted.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 0 %baredafny resolve "%S/Inputs/github-issue-38-nat-accepted.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-nat-accepted.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 0 %baredafny resolve "%S/Inputs/github-issue-38-nat-accepted.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-nat-rejected.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-nat-rejected.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-nat-rejected.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-nat-rejected.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-plain-false.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-38-plain-false.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-plain-false.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 4 %baredafny verify "%S/Inputs/github-issue-38-plain-false.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --solver-path "%z3" --verification-time-limit:60 >> "%t"
// RUN: echo "github-issue-38-rejected.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-rejected.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-rejected.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-rejected.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings >> "%t"
// RUN: echo "github-issue-38-trait.dfy (type-system-refresh:false)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-trait.dfy" --type-system-refresh:false --show-snippets:false --use-basename-for-filename --allow-warnings --general-traits:full >> "%t"
// RUN: echo "github-issue-38-trait.dfy (type-system-refresh:true)" >> "%t"
// RUN: %exits-with 2 %baredafny resolve "%S/Inputs/github-issue-38-trait.dfy" --type-system-refresh:true --show-snippets:false --use-basename-for-filename --allow-warnings --general-traits:full >> "%t"
// RUN: %diff "%s.expect" "%t"
