// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-abp.dfy" > "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-abp.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-apb.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-apb.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-bap.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-bap.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-bpa.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-bpa.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-pab.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-pab.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/original-pba.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/original-pba.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/self.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/self.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/both-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/both-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/three-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/three-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/constant.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/constant.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/function.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/function.dfy" >> "%t"
// RUN: %bounded-resolve explicit-cycle false "%S/Inputs/github-issue-44b/explicit.dfy" >> "%t"
// RUN: %bounded-resolve explicit-cycle true "%S/Inputs/github-issue-44b/explicit.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/alias.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/alias.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/inferred-subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/inferred-subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/alias-subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/alias-subset.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/subset-alias-first.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-alias-first.dfy" >> "%t"
// RUN: %bounded-resolve cycle-and-error false "%S/Inputs/github-issue-44b/unrelated-error.dfy" >> "%t"
// RUN: %bounded-resolve cycle-and-error true "%S/Inputs/github-issue-44b/unrelated-error.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained false "%S/Inputs/github-issue-44b/subset-original.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-original.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained false "%S/Inputs/github-issue-44b/subset-both-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-both-inferred.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained false "%S/Inputs/github-issue-44b/subset-self.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-self.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/subset-constant.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-constant.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/subset-function.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/subset-function.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-abp.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-abp.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-apb.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-apb.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-bap.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-bap.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-bpa.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-bpa.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-pab.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-pab.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/int-acyclic-pba.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/int-acyclic-pba.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-abp.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-abp.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-apb.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-apb.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-bap.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-bap.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-bpa.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-bpa.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-pab.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-pab.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/real-acyclic-pba.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/real-acyclic-pba.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/numeric-chains.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/numeric-chains.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/acyclic-constant.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/acyclic-constant.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/acyclic-function.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/acyclic-function.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained false "%S/Inputs/github-issue-44b/underconstrained.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained true "%S/Inputs/github-issue-44b/underconstrained.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained false "%S/Inputs/github-issue-44b/underconstrained-subset.dfy" >> "%t"
// RUN: %bounded-resolve underconstrained true "%S/Inputs/github-issue-44b/underconstrained-subset.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/generic-repeated.dfy" --general-newtypes:true >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/generic-parameter.dfy" --general-newtypes:true >> "%t"
// RUN: %bounded-resolve explicit-cycle true "%S/Inputs/github-issue-44b/generic-changing.dfy" --general-newtypes:true >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/generic-inferred-changing.dfy" --general-newtypes:true >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/generic-through-alias.dfy" --general-newtypes:true >> "%t"
// RUN: %bounded-resolve explicit-cycle false "%S/Inputs/github-issue-44b/module-attribute-explicit.dfy" >> "%t"
// RUN: %bounded-resolve explicit-cycle true "%S/Inputs/github-issue-44b/module-attribute-explicit.dfy" >> "%t"
// RUN: %bounded-resolve constraint-cycle false "%S/Inputs/github-issue-44b/module-attribute-self.dfy" >> "%t"
// RUN: %bounded-resolve constraint-cycle true "%S/Inputs/github-issue-44b/module-attribute-self.dfy" >> "%t"
// RUN: %bounded-resolve cycle false "%S/Inputs/github-issue-44b/module-attribute-inferred.dfy" >> "%t"
// RUN: %bounded-resolve cycle true "%S/Inputs/github-issue-44b/module-attribute-inferred.dfy" >> "%t"
// RUN: %bounded-resolve valid false "%S/Inputs/github-issue-44b/module-attribute-valid.dfy" >> "%t"
// RUN: %bounded-resolve valid true "%S/Inputs/github-issue-44b/module-attribute-valid.dfy" >> "%t"
// RUN: %diff "%s.expect" "%t"

// Each input is a separate process with a 30-second, startup-inclusive timeout.
// Cycle cases require normal exit 2 and a cycle diagnostic; a hang or exception fails.
// Generic source cases select the supported refreshed/general-newtypes configuration.
// The part-(a) driver, github-issue-44.dfy, remains a separate regression.
// The three pure inferred subset cases retain legacy underspecified-base diagnostics.
// Their proxy occurs-check leaves no concrete nominal redirecting-type cycle.
