using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Bpl=Microsoft.Boogie;
namespace Microsoft.Dafny;
// Diagnostic inputs are existing call argument bindings and actual caller
// checks. Never inspect body terms to generate support or reevaluate an input.
public static class NativeFrozenArgumentDiagnostic {
  public sealed class Scope {
    internal readonly List<(Bpl.AssignCmd Command,string Name,Bpl.Expr Value,int Index,HashSet<string> Reads)> Bindings=new();
    internal readonly List<Bpl.AssertCmd> Checks=new();
    internal bool OuterStable;
  }
  private static readonly List<Scope> Scopes=new();
  private static string[] Selection(){var value=Environment.GetEnvironmentVariable("OBLIGATION_DIAGNOSTIC_FROZEN_ARGUMENTS");if(value==null){return null;}var p=value.Split(':');Require(p.Length==2&&p[1]=="LemmaRemainder"&&new[]{"native-control","captured-argument-values","false-entry"}.Contains(p[0]),"Unknown selection");return p;}
  public static Scope Begin(string declaration,string callee){var p=Selection();if(p==null||p[1]!=declaration||callee!="LemmaDivInductionAuto"){return null;}var scope=new Scope();Scopes.Add(scope);return scope;}
  public static void Bind(Scope scope,Bpl.Cmd command,IReadOnlyList<object> commands){if(scope==null){return;}Require(command is Bpl.AssignCmd,"Argument was not frozen by assignment");var a=(Bpl.AssignCmd)command;Require(a.Lhss.Count==1&&a.Rhss.Count==1&&a.Lhss[0] is Bpl.SimpleAssignLhs&&ReferenceEquals(commands.Last(),a),"Unsupported binding");var name=((Bpl.SimpleAssignLhs)a.Lhss[0]).AssignedVariable.Name;Require(scope.Bindings.All(b=>b.Name!=name),"Repeated argument name");var reads=new Reads();reads.VisitExpr(a.Rhss[0]);scope.Bindings.Add((a,name,a.Rhss[0],commands.Count-1,reads.Names));}
  public static void Ready(Scope scope,IReadOnlyList<object> commands){if(scope==null){return;}Require(scope.Bindings.Count==3,"Unexpected argument count");foreach(var b in scope.Bindings){Require(ReferenceEquals(commands[b.Index],b.Command)&&NoWrites(commands.Skip(b.Index+1),b.Reads),"Captured value changed before caller proof");}scope.OuterStable=true;}
  public static void Capture(Scope scope,Bpl.PredicateCmd check,IReadOnlyList<object> preparation){if(scope==null){return;}Require(scope.OuterStable&&check is Bpl.AssertCmd,"Missing mandatory caller check");Require(scope.Bindings.All(b=>NoWrites(preparation,b.Reads)),"Captured value changed in preparation");scope.Checks.Add((Bpl.AssertCmd)check);}
  private static bool NoWrites(IEnumerable<object> commands,ISet<string> reads){foreach(var c in commands){switch(c){
    case Bpl.CommentCmd or Bpl.PredicateCmd:break;
    case Bpl.AssignCmd a:if(a.Lhss.Any(l=>l is not Bpl.SimpleAssignLhs s||reads.Contains(s.AssignedVariable.Name))){return false;}break;
    case Bpl.HavocCmd h:if(h.Vars.Any(v=>reads.Contains(v.Name))){return false;}break;
    case Bpl.IfCmd b:if(b.Attributes!=null||b.ElseIf!=null||!NoWrites(Commands(b.Thn),reads)||b.ElseBlock!=null&&!NoWrites(Commands(b.ElseBlock),reads)){return false;}break;
    default:return false;
  }}return true;}
  private static IEnumerable<object> Commands(Bpl.StmtList list){Require(list.PrefixCommands is not {Count:>0},"Unsupported prefix");var result=new List<object>();foreach(var b in list.BigBlocks){Require(b.Anonymous&&b.tc==null,"Unsupported transfer/label in call setup");result.AddRange(b.simpleCmds);if(b.ec!=null){result.Add(b.ec);}}return result;}
  private sealed class Reads:Bpl.ReadOnlyVisitor{internal readonly HashSet<string> Names=new();public override Bpl.Expr VisitIdentifierExpr(Bpl.IdentifierExpr n){Names.Add(n.Name);return n;}}
  private static string Key(Bpl.AssertCmd c,IReadOnlyDictionary<string,(Bpl.Variable Declaration,Bpl.Expr Value)> aliases=null)=>JsonSerializer.Serialize(new{expression=aliases==null?NativeFrozenArgumentFingerprint.Expression(c.Expr):NativeFrozenArgumentFingerprint.ProjectedExpression(c.Expr,aliases),attributes=NativeFrozenArgumentFingerprint.Attributes(c.Attributes,new NativeFrozenArgumentFingerprint.BindingScope()),line=c.tok.line,col=c.tok.col});
  public static void Apply(Bpl.Program program){var p=Selection();if(p==null){return;}var targets=program.TopLevelDeclarations.OfType<Bpl.Implementation>().Where(i=>i.Name=="Impl$$Std_mArithmetic_mDivMod.__default.LemmaRemainder").ToList();if(targets.Count==0){return;}Require(targets.Count==1&&Scopes.Count==1,"Unexpected target/scope count");var impl=targets.Single();var scope=Scopes.Single();Require(scope.Bindings.Count==3&&scope.Checks.Count==4&&scope.OuterStable,"Incomplete frozen caller data");var commands=impl.Blocks.SelectMany(b=>b.Cmds).ToList();var checks=commands.OfType<Bpl.AssertCmd>().ToList();Require(checks.Count==8,"Unexpected check count");var transfers=impl.Blocks.Select(b=>b.TransferCmd).ToList();var aliases=new Dictionary<string,(Bpl.Variable Declaration,Bpl.Expr Value)>();foreach(var b in scope.Bindings){var local=impl.LocVars.Single(v=>v.Name==b.Name);var assigned=((Bpl.SimpleAssignLhs)b.Command.Lhss.Single()).AssignedVariable;Require(assigned.Type!=null&&assigned.Type.Equals(local.TypedIdent.Type),"Frozen assignment representation type changed");Require(b.Value.Type==null||b.Value.Type.Equals(local.TypedIdent.Type),$"Known argument representation type changed: {b.Value.Type} versus {local.TypedIdent.Type}");Require(commands.Count(c=>ReferenceEquals(c,b.Command))==1&&scope.Checks.All(c=>commands.IndexOf(b.Command)<commands.IndexOf(c)),"Frozen binding absent or after actual check");aliases.Add(b.Name,(local,b.Value));}
    var protectedNames=new HashSet<string>(aliases.Keys.Concat(scope.Bindings.SelectMany(b=>b.Reads)));Require(scope.Bindings.All(b=>!b.Reads.Overlaps(aliases.Keys)),"Captured argument depends on another temporary");var replacement=new Replace(aliases,protectedNames);foreach(var c in checks){replacement.RejectCapture(c.Expr);}var before=checks.Select(c=>Key(c)).Order().ToArray();var projected=checks.Select(c=>Key(c,aliases)).Order().ToArray();var metadata=checks.Select(c=>c.Attributes).ToList();var originals=commands.OfType<Bpl.PredicateCmd>().ToDictionary(c=>c,c=>c.Expr,ReferenceEqualityComparer.Instance);var selected=p[0]!="native-control";
    if(selected){foreach(var c in scope.Checks){Require(c.Checksum==null&&c.SugaredCmdChecksum==null&&c.OrigExpr==null,"Unexpected pre-pass metadata");c.Expr=replacement.VisitExpr(c.Expr);}}
    var after=checks.Select(c=>Key(c)).Order().ToArray();Require(!selected||after.SequenceEqual(projected),"Actual check differs from exact frozen-value projection");Require(checks.Select(c=>c.Attributes).SequenceEqual(metadata,ReferenceEqualityComparer.Instance),"Original metadata changed");Require(commands.OfType<Bpl.PredicateCmd>().Where(c=>c is not Bpl.AssertCmd a||!scope.Checks.Contains(a)).All(c=>ReferenceEquals(c.Expr,originals[c])),"Other support/summary expression changed");Require(commands.SequenceEqual(impl.Blocks.SelectMany(b=>b.Cmds),ReferenceEqualityComparer.Instance)&&transfers.SequenceEqual(impl.Blocks.Select(b=>b.TransferCmd),ReferenceEqualityComparer.Instance),"Commands/order/transfers changed");Require(scope.Bindings.All(b=>ReferenceEquals(b.Command.Rhss.Single(),b.Value)),"Captured evaluation changed");var negative=p[0]=="false-entry";if(negative){impl.Blocks.First().Cmds.Insert(0,new Bpl.AssertCmd(impl.tok,Bpl.Expr.False));}
    var path=Environment.GetEnvironmentVariable("OBLIGATION_DIAGNOSTIC_AUDIT");Require(!string.IsNullOrEmpty(path)&&!File.Exists(path),"Missing/repeated audit");File.WriteAllText(path,JsonSerializer.Serialize(new{target=p[1],variant=p[0],actualCheckFingerprints=before,projectedOriginalCheckFingerprints=projected,actualCheckFingerprintsAfter=after,staticCheckCount=8,capturedArguments=3,callerCheckCount=4,replacedChecks=selected?4:0,bindings=scope.Bindings.Select(b=>new{name=b.Name,type=aliases[b.Name].Declaration.TypedIdent.Type.ToString(),preResolutionValueType=b.Value.Type?.ToString(),value=NativeFrozenArgumentFingerprint.Expression(b.Value),reads=b.Reads.Order().ToArray()}).ToArray(),allBindingEvaluationsRetainedExactlyOnce=true,originalTypedAssignmentTargetsRetained=true,inferredValueTypesCheckedByNormalBoogiePipeline=true,allCapturedValuesStableThroughCallSetupAndPreparation=true,binderCaptureRejected=true,allActualChecksEquivalentUnderExistingTypedBindings=true,allOriginalAttributeChainsRetainedByReference=true,allOtherSupportSummariesAndExpressionsRetainedByReference=true,allOriginalCommandsOrderAndTransfersRetained=true,noFuelPublicationGuardOrTriggerPolicyChange=true,negativeEntryAdded=negative,productPolicy=false})+"\n");
  }
  private sealed class Replace(IReadOnlyDictionary<string,(Bpl.Variable Declaration,Bpl.Expr Value)> aliases,ISet<string> protectedNames):Bpl.Duplicator {
    public override Bpl.Expr VisitIdentifierExpr(Bpl.IdentifierExpr n){if(aliases.TryGetValue(n.Name,out var a)){Require(n.Decl==null||ReferenceEquals(n.Decl,a.Declaration),"Ambiguous actual parameter identity");return a.Value;}return base.VisitIdentifierExpr(n);}
    public void RejectCapture(Bpl.Expr e){switch(e){case Bpl.IdentifierExpr or Bpl.LiteralExpr:return;case Bpl.OldExpr old:RejectCapture(old.Expr);return;case Bpl.NAryExpr app:foreach(var a in app.Args){RejectCapture(a);}return;case Bpl.QuantifierExpr q:Binders(q.Dummies);Attributes(q.Attributes);RejectCapture(q.Body);for(var t=q.Triggers;t!=null;t=t.Next){foreach(var x in t.Tr){RejectCapture(x);}}return;case Bpl.LambdaExpr l:Binders(l.Dummies);Attributes(l.Attributes);RejectCapture(l.Body);return;case Bpl.LetExpr let:Binders(let.Dummies);foreach(var x in let.Rhss){RejectCapture(x);}RejectCapture(let.Body);return;default:throw new InvalidOperationException("Unsupported expression in captured-value projection");}}
    private void Binders(IEnumerable<Bpl.Variable> variables){Require(variables.All(v=>!protectedNames.Contains(v.Name)),"Captured value would acquire a binder");}
    private void Attributes(Bpl.QKeyValue attrs){for(var a=attrs;a!=null;a=a.Next){foreach(var e in a.Params.OfType<Bpl.Expr>()){RejectCapture(e);}}}
  }
  private static void Require(bool condition,string message){if(!condition){throw new InvalidOperationException(message);}}
}
